title:              TKVTV
email:              your-email@example.com
description:        A Blog Theme by Start Bootstrap
author:             takagotch
baseurl:            "/page169"
url:                "https://takagotch.github.io"

# Social Profiles
twitter_username:   
github_username:    takagotch
facebook_username:  tkgcci
instagram_username:  
linkedin_username:  takagotch

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


